name: validate CITATION.cff

on:
  push:
    branches: ['*']
    paths:
      - 'CITATION.cff'
  pull_request:
    branches: ['*']
    paths:
      - 'CITATION.cff'

jobs:

  validate_cff:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Check whether the citation metadata from CITATION.cff is valid
      uses: citation-file-format/cffconvert-github-action@2.0.0
      with:
        args: "--validate"
